from django.urls import path
from . import views

urlpatterns = [
    path('', views.manage_projects, name='manage_projects'),
    path('create/', views.create_project, name='create_project'),
    path('<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path('<int:project_id>/events/', views.manage_events, name='manage_events'),
    path('<int:project_id>/events/create/', views.create_event, name='create_event'),
    path('<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('event/<int:event_id>/edit/', views.edit_event, name='edit_event'),
    path('event/<int:event_id>/delete/', views.delete_event, name='delete_event'),
    path('events/<int:event_id>/copy_addresses/', views.copy_addresses, name='copy_addresses'),
    path('events/address/<int:address_id>/delete/', views.delete_event_address, name='delete_event_address'),
    path('event/<int:event_id>/add_addresses/', views.add_new_addresses, name='add_new_addresses'),
    path('update-address-order/', views.update_address_order, name='update_address_order'), # обновление порядка адреса в списке адресов события
    path('project/<int:project_id>/get_coordinates/', views.get_coordinates, name='get_coordinates'),
    path('project/<int:project_id>/delete_addresses/', views.delete_addresses, name='delete_addresses'),
    path('project/<int:project_id>/edit_address_name/', views.edit_address_name, name='edit_address_name'),
    path('project/<int:project_id>/delete_address/', views.delete_address, name='delete_address'),
    path('project/<int:project_id>/update_addresses/', views.update_addresses, name='update_addresses'),
    path('assigned-events/', views.assigned_events_list, name='assigned_events_list'),
    path('assigned-events/remove/<int:event_id>/', views.remove_assigned_event, name='event_remove'),
    path('event/<int:event_id>/update-executors/', views.update_event_executors, name='update_event_executors'),
    path('remove_executor/', views.remove_executor, name='remove_executor'),
    path('assign_executor/', views.assign_executor, name='assign_executor'),
    path('confirm_executor/', views.confirm_executor, name='confirm_executor'),
    path('complete-event/', views.complete_event, name='complete_event'),
    path('start-event/', views.start_event, name='start_event'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('calculate_optimal_route/', views.calculate_optimal_route, name='calculate_optimal_route'),
    path('events/control/', views.events_control, name='events_control'),
    path('get-remaining-requests/', views.get_remaining_requests, name='get_remaining_requests'),
    path('event/<int:event_id>/address/<int:address_id>/upload/', views.upload_photos, name='upload_photos'),
    path('event/<int:event_id>/view_photos/', views.view_photos, name='view_photos'),
    path('fetch_executor_photos/', views.fetch_executor_photos, name='fetch_executor_photos'),
    path('download_executor_photos/', views.download_executor_photos, name='download_executor_photos'),
    path('get-addresses/', views.get_addresses_for_events, name='get_addresses_for_events'),
    path('save_combined_address_order/', views.save_combined_address_order, name='save_combined_address_order'),
    path('optimize-route/', views.optimize_route, name='optimize_route'),
    path('upload_combined_addresses_photos/', views.upload_combined_addresses_photos, name='upload_combined_addresses_photos'),
]