# Generated by Django 5.1.3 on 2024-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1000)),
                ('last_reset', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
