# Generated by Django 5.1.3 on 2024-11-25 06:39

from django.db import migrations


def fill_user(apps, schema_editor):
    RequestCounter = apps.get_model('projects', 'RequestCounter')
    User = apps.get_model('auth', 'User')

    # Получите всех пользователей
    users = list(User.objects.all())
    for i, counter in enumerate(RequestCounter.objects.all()):
        # Присваиваем текущему счетчику пользователя из списка пользователей
        if i < len(users):
            counter.user = users[i]
            counter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_requestcounter_user'),  # Замените на вашу миграцию
    ]

    operations = [
        migrations.RunPython(fill_user),
    ]