# Generated by Django 5.1.3 on 2024-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_eventaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventaddress',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='eventaddress',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
