# Generated by Django 5.1.3 on 2024-12-03 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_event_assigned_user_event_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='events_as_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
