# Generated by Django 5.1.3 on 2024-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_event_assigned_user_event_assigned_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
