# Generated by Django 5.1.3 on 2024-12-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_address_options_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
