# Generated by Django 5.1.3 on 2024-12-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_eventuserlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventUserLink',
        ),
    ]
