# Generated by Django 5.1.3 on 2024-12-06 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_event_assigned_users_eventuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='events_as_assignee', through='projects.EventUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
