# Generated by Django 5.1.3 on 2024-12-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_event_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='status',
            field=models.CharField(choices=[('chosen', 'Выбран'), ('assigned', 'Назначен'), ('confirmed', 'Подтвержден'), ('declined', 'Отказ')], default='chosen', max_length=10),
        ),
    ]
