# Generated by Django 5.1.3 on 2024-12-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_eventuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='status',
            field=models.CharField(choices=[('chosen', 'Выбран'), ('assigned', 'Назначен'), ('confirmed', 'Подтвержден'), ('declined', 'Отказ'), ('in_progress', 'В работе'), ('completed', 'Завершён')], default='chosen', max_length=11),
        ),
    ]
