# Generated by Django 5.1.3 on 2024-12-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
    ]
