# Generated by Django 5.1.3 on 2024-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_remove_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='status',
            field=models.CharField(choices=[('chosen', 'Выбран'), ('assigned', 'Назначено'), ('confirmed', 'Подтверждено'), ('declined', 'Отказ'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='chosen', max_length=11),
        ),
    ]
