# Generated by Django 5.1.3 on 2024-12-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_eventuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('assigned', 'Назначено'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='created', max_length=11),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_days',
            field=models.IntegerField(),
        ),
    ]
