# Generated by Django 5.1.3 on 2024-11-22 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0004_project_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
