# Generated by Django 5.1.3 on 2024-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0005_remove_project_user_delete_event_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
