# Generated by Django 5.1.3 on 2024-11-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0006_profile_api_key_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
