# Generated by Django 5.1.3 on 2024-11-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0007_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
