# Generated by Django 5.1.3 on 2024-11-29 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0008_profile_first_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_address', models.CharField(max_length=255)),
                ('district', models.CharField(choices=[('САО', 'Северный административный округ'), ('ВАО', 'Восточный административный округ'), ('ЮАО', 'Южный административный округ'), ('ЗАО', 'Западный административный округ')], max_length=3)),
                ('api_key', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
