# Generated by Django 5.1.3 on 2024-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0009_executorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executorprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='executorprofile',
            name='district',
            field=models.CharField(choices=[('САО', 'САО'), ('ВАО', 'ВАО'), ('ЮАО', 'ЮАО'), ('ЗАО', 'ЗАО')], max_length=3),
        ),
        migrations.AlterField(
            model_name='executorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
