# Generated by Django 5.1.3 on 2024-12-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0010_alter_executorprofile_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
