# Generated by Django 5.1.3 on 2024-12-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0011_executorprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executorprofile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='executorprofile',
            name='start_address',
        ),
    ]
